export const permittedCountries = [
  { label: "Rest of the World", code: "ROW" },
  { label: "Argentina", code: "AR" },
  { label: "Australia", code: "AU" },
  { label: "Austria", code: "AT" },
  { label: "Bangladesh", code: "BD" },
  { label: "Belgium", code: "BE" },
  { label: "Bolivia", code: "BO" },
  { label: "Bosnia and Herzegovina", code: "BA" },
  { label: "Brazil", code: "BR" },
  { label: "Bulgaria", code: "BG" },
  { label: "Canada", code: "CA" },
  { label: "Chile", code: "CL" },
  { label: "Colombia", code: "CO" },
  { label: "Costa Rica", code: "CR" },
  { label: "Croatia", code: "HR" },
  { label: "Cyprus", code: "CY" },
  { label: "Czech Republic", code: "CZ" },
  { label: "Denmark", code: "DK" },
  { label: "Dominican Republic", code: "DO" },
  { label: "Ecuador", code: "EC" },
  { label: "Egypt", code: "EG" },
  { label: "El Salvador", code: "SV" },
  { label: "Estonia", code: "EE" },
  { label: "Finland", code: "FI" },
  { label: "France", code: "FR" },
  { label: "Georgia", code: "GE" },
  { label: "Germany", code: "DE" },
  { label: "Greece", code: "GR" },
  { label: "Honduras", code: "HN" },
  { label: "Hong Kong", code: "HK" },
  { label: "Hungary", code: "HU" },
  { label: "Iceland", code: "IS" },
  { label: "India", code: "IN" },
  { label: "Indonesia", code: "ID" },
  { label: "Ireland", code: "IE" },
  { label: "Israel", code: "IL" },
  { label: "Italy", code: "IT" },
  { label: "Japan", code: "JP" },
  { label: "Kazakhstan", code: "KZ" },
  { label: "Kuwait", code: "KW" },
  { label: "Latvia", code: "LV" },
  { label: "Lebanon", code: "LB" },
  { label: "Lithuania", code: "LT" },
  { label: "Luxembourg", code: "LU" },
  { label: "Macau", code: "MO" },
  { label: "Malaysia", code: "MY" },
  { label: "Malta", code: "MT" },
  { label: "Mexico", code: "MX" },
  { label: "Mongolia" },
  { label: "Netherlands", code: "NL" },
  { label: "New Zealand", code: "NZ" },
  { label: "Norway", code: "NO" },
  { label: "Panama", code: "PA" },
  { label: "Paraguay", code: "PY" },
  { label: "Peru", code: "PE" },
  { label: "Philippines", code: "PH" },
  { label: "Poland", code: "PL" },
  { label: "Portugal", code: "PT" },
  { label: "Puerto Rico", code: "PR" },
  { label: "Qatar", code: "QA" },
  { label: "Romania", code: "RO" },
  { label: "Saudi Arabia", code: "SA" },
  { label: "Serbia", code: "RS" },
  { label: "Singapore", code: "SG" },
  { label: "Slovakia", code: "SK" },
  { label: "South Africa", code: "ZA" },
  { label: "South Korea", code: "KR" },
  { label: "Spain", code: "ES" },
  { label: "Sweden", code: "SE" },
  { label: "Switzerland", code: "CH" },
  { label: "Taiwan", code: "TW" },
  { label: "Thailand", code: "TH" },
  { label: "Trinidad & Tobago", code: "TT" },
  { label: "Turkey", code: "TR" },
  { label: "Ukraine", code: "UA" },
  { label: "United Arab Emirates", code: "AE" },
  { label: "United Kingdom", code: "GB" },
  { label: "United States of America", code: "US" },
  { label: "Uruguay", code: "UY" },
  { label: "Venezuela", code: "VE" },
  { label: "Vietnam", code: "VN" },
]